enigma:
  client:
    two-way-enabled: true
    enigma-base-url: "https://localhost:11443/enigma/"
    # key store
    key-store: classpath:enigmaclient.p12
    key-store-password: 2secure4u
    key-store-type: pkcs12
    key-store-alias: enigmaclient
    # trust store
    trust-store: classpath:enigmaclient.p12
    trust-store-password: 2secure4u
    trust-store-type: pkcs12
    oauth2:
      client-id: enigma-user
      oauth2-token-uri: "https://localhost:12443/auth/realms/enigma/protocol/openid-connect/token"
      client-secret: "bcd4713d-3822-4119-a976-32bc0ef2596a"
      trust-store: classpath:enigmaclient.p12
      trust-store-password: 2secure4u
      trust-store-type: pkcs12
